### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by leijdekkers** [Kyash/rx-keyboard-detector#1]
Hi

I use your library in a fragment but if i pop the fragment and then start it again the app crashes. It looks like that resources are not released. I tried to do this in onPause() of the fragment:  KeyboardDetector(baseActivity).observe().unsubscribeOn(AndroidSchedulers.mainThread())

but no luck. Any suggestions welcome.

**Comment by konifar** [comment]
@leijdekkers Hi, thanks for using this library and reporting the issue.
I'll try to reproduce it. Can you put the stacktrace here? It would be helpful for us.

**Comment by konifar** [comment]
Actually I can not reproduce it.
But I guess `rootView` would be null, right? https://github.com/Kyash/rx-keyboard-detector/blob/master/library/src/main/java/co/kyash/rkd/KeyboardDetector.kt#L36

If it's true, I can fix it by checking `rootView` is null.

**Comment by leijdekkers** [comment]
I might have fixed it by checking if the view i want to hide on keyboard shown is not null. But always good to check in your code if rootview is not null! Thanks

**Comment by konifar** [comment]
Good. So then I'll release new version today (JST). Thanks!

**Comment by konifar** [comment]
@leijdekkers Hi, I released 0.1.2 just now. Can you try to update? Thanks!
